import type { Metadata } from "next";
import { Space_Grotesk, Google_Sans, DM_Mono } from "next/font/google";
import "./globals.css";
import Transition from "./components/transition/Transition";


const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  weight: "400",
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${spaceGrotesk.variable} ${googleSans.variable} ${dmMono.variable} antialiased`}
      >
        <Transition>
          {children}
        </Transition>
      </body>
    </html>
  );
}
